In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
a, b = 10, 20

In [2]:
print(a, b)

10 20


In [3]:
a, b = b, a

In [4]:
print(a,b)

20 10


In [11]:
lt = [[1,2],[3,4],[5,6]]
print(lt)


[[1, 2], [3, 4], [5, 6]]


In [14]:
lt[[2,1]] = lt[[1,2]]

TypeError: list indices must be integers or slices, not list

In [13]:
lt

[[1, 2], [3, 4], [5, 6]]

In [16]:
arr = np.array(lt)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr[[2,1]] = arr[[1,2]]
print(arr)

[[1 2]
 [5 6]
 [3 4]]


---

Assignment Question (Week-2)

In [8]:
def get_index_first_non_zero_value_from_column(M, column, starting_row):
    # Get the column array starting from the specified row
    column_array = M[starting_row:,column]
    print(column_array)
    for i, val in enumerate(column_array):
        # Iterate over every value in the column array. 
        # To check for non-zero values, you must always use np.isclose instead of doing "val == 0".
        if not np.isclose(val, 0, atol = 1e-5):
            # If one non zero value is found, then adjust the index to match the correct index in the matrix and return it.
            index = i + starting_row
            return index
    # If no non-zero value is found below it, return -1.
    return -1

In [9]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

[[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]


In [10]:
print(get_index_first_non_zero_value_from_column(N, column = -1, starting_row = 2))

[0 7 4]
3
